### ISSUE TITLE
Demo failed with lastest Quarkus

### ISSUE THREAD

**Issue by zhfeng** [quarkiverse/quarkus-dapr#34]
```
2022-06-13 05:42:20,583 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.lang.NoSuchMethodException: io.grpc.netty.UdsNettyChannelProvider.<init>()
	at java.lang.Class.getConstructor0(DynamicHub.java:3349)
	at java.lang.Class.getConstructor(DynamicHub.java:2151)
	at io.grpc.ServiceProviders.createForHardCoded(ServiceProviders.java:136)
	at io.grpc.ServiceProviders.getCandidatesViaHardCoded(ServiceProviders.java:125)
	at io.grpc.InternalServiceProviders.getCandidatesViaHardCoded(InternalServiceProviders.java:63)
	at io.grpc.ServiceProviders.loadAll(ServiceProviders.java:28)
	at io.grpc.ManagedChannelRegistry.getDefaultRegistry(ManagedChannelRegistry.java:101)
	at io.grpc.ManagedChannelProvider.provider(ManagedChannelProvider.java:43)
	at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39)
	at io.dapr.client.DaprClientBuilder.buildDaprClientGrpc(DaprClientBuilder.java:160)
	at io.dapr.client.DaprClientBuilder.buildDaprClient(DaprClientBuilder.java:143)
	at io.dapr.client.DaprClientBuilder.build(DaprClientBuilder.java:114)
	at io.quarkiverse.dapr.runtime.DaprProducer.daprClient(DaprProducer.java:44)
```
CI failures https://github.com/quarkiverse/quarkus-dapr/actions/runs/2486169031

It seems that it is missing the refelction for `io.grpc.netty.UdsNettyChannelProvider`

**Comment by zhfeng** [comment]
It seems resolved by quarkus.
